app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::auth();

//Route::get('dataset/datos', 'DatasetController@datos');
Route::post('dataset/datos2', 'DatasetController@datos2');
Route::get('dataset/cat/{id}', 'DatasetController@showByCat');
Route::get('dataset/subcat/{id}', 'DatasetController@showBySubcat');


Route::get('/home', 'HomeController@index');
Route::resource('category', 'CategoryController');
Route::resource('subcategory', 'SubcategoryController');
Route::resource('dataset', 'DatasetController');



Route::get('/categories', function() {
    return "Hello there!";
});

app/Dataset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dataset extends Model
{
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function subcategory()
    {
        return $this->belongsTo('App\Subcategory');
    }
}

app/Http/Controllers/DatasetController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Dataset;
use App\Subcategory;
use Illuminate\Auth\Access\Response;
use Illuminate\Http\Request;
//use Illuminate\Support\Facades\Request;

//para poder usar el request ajax

use App\Http\Requests;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Input;//para poder usar input post ajax

class DatasetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datasets = Dataset::all();
        return view('entities.dataset.index',["datasets"=>$datasets]);
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('entities.dataset.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dataset = new Dataset();
        $dataset->name = $request->nombre;
        $dataset->information = $request->informacion;
        $dataset->table = $request->tabla;
        $dataset->downloads = $request->descargas;
        $dataset->category_id = $request->categoria;
        $dataset->subcategory_id = $request->subcategoria;

        $dataset->save();
        return redirect('dataset');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

//        if (Request::ajax())
//        {
//            $data[] = array('label'=> 'Raval2','Poblacion'=> 9);
//            $data[] = array('label'=>'proba','id'=>session('key'));
//            return $data;
       // }
        $dataset = Dataset::find($id);
        $downloads = $porciones = explode(",", $dataset->downloads);
        session(['tabla' => $dataset->table]);
        //$result = DB::table($dataset->table)->pluck('numero_personas');
       // $result2 = DB::table($dataset->table)->select('numero_personas', 'barrioOrigen')->groupBy('barrioOrigen')->get();
        $data = array('Mushrooms'=> 3,
            'Onions'=> 1
        );
       // var_dump($data);

        $columns = DB::getSchemaBuilder()->getColumnListing($dataset->table);
        //print_r($columns);
        $rows = DB::table($dataset->table)->paginate(15);

        return view('entities.dataset.show',["rows"=>$rows,'columns'=>$columns, 'data'=>$data, "url" => config('variables.base_url'), "downloads"=>$downloads, "directorio" => "uploads/".$dataset->table."/"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showByCat($id){
        $datasets = Category::find($id)->datasets;

        return view('entities.dataset.index',["datasets"=>$datasets]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function showBySubcat($id){
        $datasets = Subcategory::find($id)->datasets;

        return view('entities.dataset.index',["datasets"=>$datasets]);
    }

    
//    public function datos()
//    {
//
//        $data[] = array('label'=> 'Raval','Poblacion'=> 5);
//        $data[] = array('label'=> 'Raval2','Poblacion'=> session('tabla'));
//        return $data;
//    }



    public function datos2()
    {
//        if (Request::ajax())
//        {
            $label = Input::get('label');
            $value = Input::get('value');


            $result2 = DB::table(session('tabla'))->select(DB::raw('CONVERT(SUM('.$value.'), SIGNED INTEGER) as '.$value.', '.$label))->groupBy($label)->get();


           // $result2 = DB::table(session('tabla'))->select($label, SUM($value))->groupBy($label)->get();

            $data[] = array('label'=>'proba','id'=>5);
            return $result2;
       // }


        $data[] = array('label'=> 'Raval2','Poblacion'=> 5);
        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/entities/dataset/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Crear dataset</h1>

    <form action="{{ route('dataset.store')}}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control" type="text" name="nombre" id="nombre">
        </div>

        <div class="form-group">
            <label for="informacion">Informacion</label>
            <input class="form-control" type="text" name="informacion" id="informacion">
        </div>
        <div class="form-group">
            <label for="tabla">Tabla</label>
            <input class="form-control" type="text" name="tabla" id="tabla">
        </div>

        <div class="form-group">
            <label for="descargas">Descargas</label>
            <input class="form-control" type="text" name="descargas" id="descargas">
        </div>

        <div class="form-group">
            <label for="categoria">Categoria</label>
            <input class="form-control" type="text" name="categoria" id="categoria">
        </div>

        <div class="form-group">
            <label for="subcategoria">Subcategoria</label>
            <input class="form-control" type="text" name="subcategoria" id="subcategoria">
        </div>

        <button class="btn btn-default" type="submit">Enviar</button>
        <input type="hidden" value="{{Session::token()}}" name="_token">

    </form>
</div>
@endsection

resources/views/entities/dataset/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col s12 titulo1 z-depth-1">
            <div class="container">
                <h3 class="center white-text">Listado de datasets</h3>
            </div>
        </div>
    </div>
    <div class="container">


        @if(count($datasets))
            <div class="collection">

                @foreach($datasets as $dataset)

                        <a class="collection-item" href="{{route('dataset.show',$dataset->id)}}" class="collection-item">{{$dataset->name}}<i class="material-icons secondary-content">assignment</i></a>

                @endforeach
            </div>
        @else
            <h3>No hay datasets aún.</h3>
        @endif
    </div>
@endsection

resources/views/entities/dataset/show.blade.php
@extends('layouts.app')
@section('content')

    <script type="text/javascript">
        var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
        // Load the Visualization API and the corechart package.
        google.charts.load('current', {'packages': ['corechart']});

        function pintarGrafica() {

            var label = $('input[name=group1]:checked', '#label').val();
            var value = $('input[name=group2]:checked', '#value').val();

            var chart = $('select#chartType').val();





            if(chart == 'pie'){
                google.charts.setOnLoadCallback(drawChart(label, value));
            }else if(chart == 'bar'){
                google.charts.setOnLoadCallback(drawBarChart(label, value));
            }
            // Set a callback to run when the Google Visualization API is loaded.
            //google.charts.setOnLoadCallback(drawChart(label, value));

            function drawChart(label, value) {
                $("#chart_div").css("border","6px solid #26A69A");

                var datos2 = $.ajax({
                    url: "datos2",
                    type: 'post',
                    data: {_token: CSRF_TOKEN, 'label': label, 'value': value},
                    dataType: 'JSON',
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('X-CSRF-TOKEN', $("#token").attr('content'));
                    },
                    async: false

                }).done(function (results) {

                    // Create the data table.
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Topping');
                    data.addColumn('number', 'Slices');

                    for (var i in results) {
                        data.addRow([results[i][label], results[i][value]]);
                    }
                    // Instantiate and draw our chart, passing in some options.
                    var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
                    // Set chart options
                    var options = {
                        'title': 'RESULTADO',
                        'width': 800,
                        'height': 800,
                        is3D: true,
                        legend: {position: 'right'},
                        pieSliceText: 'none',
                        //pieHole: 0.4,
                    };
                    chart.draw(data, options);
                });
            }
            function drawBarChart() {


                var datos2 = $.ajax({
                    url: "datos2",
                    type: 'post',
                    data: {_token: CSRF_TOKEN, 'label': label, 'value': value},
                    dataType: 'JSON',
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader('X-CSRF-TOKEN', $("#token").attr('content'));
                    },
                    async: false

                }).done(function (results) {

                    // Create the data table.
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Topping');
                    data.addColumn('number', 'Slices');

                    for (var i in results) {
                        data.addRow([results[i][label], results[i][value]]);
                    }
                    // Instantiate and draw our chart, passing in some options.
                    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
                    // Set chart options


                    // set inner height to 30 pixels per row
                    var chartAreaHeight = data.getNumberOfRows() * 30;
                    // add padding to outer height to accomodate title, axis labels, etc
                    var chartHeight = chartAreaHeight + 80;
                    var chart = new google.visualization.BarChart(document.querySelector('#chart_div'));
                    var options = {
                        title: 'cabecera',
                        width: 1000,
                        height: chartHeight,
                        chartArea: {
                            height: chartAreaHeight
                        },
                        hAxis: {
                            title: 'titulo haxis',
                            minValue: 0
                        },
                        vAxis: {
                            title: 'City'
                        }
                    };
                    chart.draw(data, options);
                });
            }
        }

    </script>


    <div class="row">
        <div class="col s12 titulo1 z-depth-1">
            <div class="container">
                <h3 class="center white-text">Listado de datasets</h3>


            </div>
        </div>
    </div>
    <div class="container">

        <div class="row">
            <div class="col s12">
                <ul class="tabs">
                    <li class="tab col s3"><a href="#test1">Tabla</a></li>
                    <li class="tab col s3"><a href="#test2">Gráficas</a></li>
                    <li class="tab col s3"><a href="#test3">Descargas</a></li>
                </ul>
            </div>
            {{--<a href="#" id="get">Get</a>--}}
            <div id="test1" class="col s12">

                <table class="highlight">
                    <thead>
                    <tr>
                        @for ($i = 1; $i < count($columns); $i++)
                            <th>{{ $columns[$i] }}</th>
                        @endfor

                    </tr>
                    </thead>

                    <tbody>


                    @foreach($rows as $row)
                        <tr>
                            @for ($i = 1; $i < count($columns); $i++)
                                <td>{{ $row->$columns[$i] }}</td>
                        @endfor
                        <tr>
                    @endforeach

                    </tbody>
                </table>

                <div class="row">
                    <div class="col s12 center">
                        <?php echo $rows->links(); ?>
                    </div>
                </div>
            </div>

            <div id="test2" class="col s12">

                <div class="row">
                    <div class="input-field col s12">

                        <select id="chartType">
                            <option value="" disabled selected>Escoje gráfica</option>
                            <option value="pie">Pie</option>
                            <option value="bar">Bar</option>
                            <option value="bubble">Bubble</option>
                        </select>
                        <label>Escoje gráfica</label>
                    </div>

                    <div class="input-field col s6">

                        <h4>Escoje la etiqueta</h4>
                        <form id="label" action="#">
                            @for ($i = 1; $i < count($columns); $i++)
                                <p>
                                    <input name="group1" type="radio" id="{{ $columns[$i] }}-label"
                                           value="{{ $columns[$i] }}"/>
                                    <label for="{{ $columns[$i] }}-label">{{ $columns[$i] }}</label>
                                </p>
                            @endfor
                        </form>

                    </div>

                    <div class="input-field col s6">

                        <h4>Escoje los valores</h4>
                        <form id="value" action="#">
                            @for ($i = 1; $i < count($columns); $i++)

                                <p>
                                    <input name="group2" type="radio" id="{{ $columns[$i] }}-value"
                                           value="{{ $columns[$i] }}" disabled/>
                                    <label for="{{ $columns[$i] }}-value">{{ $columns[$i] }}</label>
                                </p>
                            @endfor
                        </form>

                    </div>

                </div>

                <a id="pintar" class="waves-effect waves-light btn-large">
                    <i class="material-icons right">send</i>
                    Pintar
                </a>

                <div class="row">
                    <div id='chart_div' ></div>
                </div>


            </div>
            <div id="test3" class="col s12">

                <ul class="collection with-header">
                    @foreach($downloads as $download)
                        <a href="{{$url}}{{$directorio}}{{$download}}">
                            <li class="collection-item">
                                <div>
                                    {{$download}}
                                    <a href="{{$url}}{{$directorio}}{{$download}}" class="secondary-content">
                                        <i class="material-icons">get_app</i>
                                    </a>
                                </div>
                            </li>
                        </a>
                    @endforeach
                </ul>

            </div>
        </div>


    </div>
    <script>
        $("#pintar").on('click', function () {

            if($('select#chartType').val() == null){
                sweetAlert("AVISO", "Debes seleccionar un tipo de gráfica", "error");
            }else{
                pintarGrafica();
            }


        });
        $('select#chartType').change(function() {
           // console.log($(this).val())
        });


        $('#label input').on('change', function () {
            if ($("#value input[name=group2]").is(":checked")) {
                //alert("Los 2 check");
            } else {
                $("#value input:radio").attr('disabled', false);
            }
        });


    </script>
@endsection