app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::auth();

//Route::get('dataset/datos', 'DatasetController@datos');
Route::post('dataset/datos2', 'DatasetController@datos2');
Route::get('dataset/cat/{id}', 'DatasetController@showByCat');
Route::get('dataset/subcat/{id}', 'DatasetController@showBySubcat');


Route::get('/home', 'HomeController@index');
Route::resource('category', 'CategoryController');
Route::resource('subcategory', 'SubcategoryController');
Route::resource('dataset', 'DatasetController');



Route::get('/categories', function() {
    return "Hello there!";
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function subcategories()
    {
        return $this->hasMany('App\Subcategory');
    }

    public function datasets()
    {
        return $this->hasMany('App\Dataset');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        $resultado = array();

        //cada categoria
        foreach ($categories as $category){
            $subcategoriesaux=Category::find($category['id'])->subcategories;
            $subresult=array();

            //cada subcategoria de la categoria
            foreach ($subcategoriesaux as $subcategory){
                $subresult[]=array('name'=>$subcategory['name'],'id'=>$subcategory['id']);
            }

            $resultado[]= array(
                'id'=>$category['id'],
                'name'=>$category['name'],
                'information'=>$category['information'],
                'subcategories'=>$subresult
                );

        }

        //print_r($resultado);
        return view('entities.category.index', ['resultado'=>$resultado]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('entities.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new Category();
        $category->name = $request->nombre;
        $category->information = $request->informacion;
        $category->image = $request->imagen;

        $category->save();
        return redirect('category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/entities/category/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Crear categoria</h1>

    <form action="{{ route('category.store')}}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control" type="text" name="nombre" id="nombre">
        </div>

        <div class="form-group">
            <label for="informacion">Informacion</label>
            <input class="form-control" type="text" name="informacion" id="informacion">
        </div>
        <div class="form-group">
            <label for="imagen">Imagen</label>
            <input class="form-control" type="text" name="imagen" id="imagen" value="/uploads">
        </div>

        <button class="btn btn-default" type="submit">Enviar</button>
        <input type="hidden" value="{{Session::token()}}" name="_token">
    </form>
</div>
@endsection

resources/views/entities/category/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col s12 titulo1 z-depth-1">
            <div class="container">
                <h3 class="center white-text">Listado de categorías</h3>
                </div>
        </div>
        </div>
    <div class="container">


            {{--@foreach($categories as $category)--}}

                    {{--{{$category->name}}--}}
            {{--@endforeach--}}

        {{--@foreach($resultado as $categoria)--}}
            {{--<h3>{{$categoria['name']}}</h3>--}}
            {{--Subcategorías:--}}
            {{--@foreach($categoria['subcategories'] as $subcategoria)--}}
            {{--{{$subcategoria['name']}},--}}
            {{--@endforeach--}}
        {{--@endforeach--}}

        <div class="row">
        @foreach($resultado as $categoria)

                <div class="col s12 m6">
                    <div class="card blue darken-3 z-depth-2">
                        <div class="card-content white-text">
                            <span class="card-title"> <a href="{{url('dataset/cat',$categoria['id'])}}">{{$categoria['name']}}</a></span>
                            <p>{{$categoria['information']}}</p>
                        </div>
                        <div class="card-action">
                            <a class='dropdown-button btn' href='#' data-activates='{!! str_replace(' ', '_', $categoria['name']) !!}'>Subcategorías</a>
                            <ul id='{!! str_replace(' ', '_', $categoria['name']) !!}' class='dropdown-content'>
                                @foreach($categoria['subcategories'] as $subcategoria)
                                    <li><a href="{{url('dataset/subcat',$subcategoria['id'])}}">{{$subcategoria['name']}}</a></li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>



        @endforeach
    </div>

    </div>
@endsection