app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('inicio');

Route::auth();

//Route::get('dataset/datos', 'DatasetController@datos');
Route::post('dataset/datos2', 'DatasetController@datos2');
Route::get('dataset/cat/{id}', 'DatasetController@showByCat');
Route::get('dataset/subcat/{id}', 'DatasetController@showBySubcat');


Route::get('/home', 'HomeController@index');
Route::resource('category', 'CategoryController');
Route::resource('subcategory', 'SubcategoryController');
Route::resource('dataset', 'DatasetController');



Route::get('/categories', function() {
    return "Hello there!";
});

app/Subcategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function datasets()
    {
        return $this->hasMany('App\Dataset');
    }
}

app/Http/Controllers/SubcategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Subcategory;
use Illuminate\Http\Request;

use App\Http\Requests;

class SubcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories = Subcategory::all();
        return view('entities.subcategory.index',["subcategories"=>$subcategories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('entities.subcategory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $subcategory = new Subcategory();
        $subcategory->name = $request->nombre;
        $subcategory->information = $request->informacion;
        $subcategory->image = $request->imagen;
        $subcategory->category_id = $request->categoria;
        $subcategory->save();
        return redirect('category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/entities/subcategory/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <h1>Crear subcategoria</h1>

    <form action="{{ route('subcategory.store')}}" method="post">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input class="form-control" type="text" name="nombre" id="nombre">
        </div>

        <div class="form-group">
            <label for="informacion">Informacion</label>
            <input class="form-control" type="text" name="informacion" id="informacion">
        </div>
        <div class="form-group">
            <label for="imagen">Imagen</label>
            <input class="form-control" type="text" name="imagen" id="imagen" value="/uploads">
        </div>

        <div class="form-group">
            <label for="categoria">Categoria</label>
            <input class="form-control" type="text" name="categoria" id="categoria">
        </div>

        <button class="btn btn-default" type="submit">Enviar</button>
        <input type="hidden" value="{{Session::token()}}" name="_token">
    </form>
</div>
@endsection

resources/views/entities/subcategory/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col s12 titulo1 z-depth-1">
            <div class="container">
                <h3 class="center white-text">Listado de subcategorias</h3>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="row">
            @foreach($subcategories as $subcategory)

                <div class="col s12 m6">
                    <div class="card blue darken-3 z-depth-2">
                        <div class="card-content white-text">
                            <span class="card-title"><a href="{{url('dataset/subcat',$subcategory->id)}}">{{$subcategory->name}}</a></span>
                            <p>{{$subcategory->information}}</p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

    </div>
@endsection